#!/usr/bin/perl

use strict;
use warnings;

use Getopt::Long;
use Pngcam::Render;

my $width;
my $height;
my $border = 32; # px
my $bottom;
my $png;

my $quiet;

GetOptions(
    'border=f' => \$border,
    'width=f' => \$width,
    'height=f' => \$height,
    'bottom' => \$bottom,
    'png=s' => \$png,

    'quiet' => \$quiet,

    'help' => sub { help() },
    'usage' => sub { help() },
) or help();

help() if @ARGV != 1;
my $stl_file = shift @ARGV;

$png ||= "$stl_file.png";
$width = 400 if !defined $width && !defined $height;

my $render = Pngcam::Render->new(
    stl_file => $stl_file,

    border => $border,
    width => $width,
    height => $height,
    bottom => $bottom,

    quiet => $quiet,
);
$render->run;
$render->save($png);

sub help {
    print qq{Usage: pngcam-render [options] STLFILE

This program will read in the STLFILE and render it to a heightmap.

Options:

    --border PX
        Draw a border around the part.
        Default: 32

    --width PX
        Set the width of the part in pixels. If height is not specified, height will be calculated
        automatically to maintain aspect ratio. If neither are specified, width=400px is assumed.
        The output image will be this wide, plus a border on both sides.
        Default: 400

    --height PX
        Set the height of the part in pixels. If width is not specified, width will be calculated
        automatically to maintain aspect ratio. If neither are specified, width=400px is assumed.
        The output image will be this talg, plus a border on both sides.
        Default: N/A

    --bottom
        View from the bottom, as if the part were rotated through 180 degrees around the Y axis.
        Default: viewed from the top

    --png PNGFILE
        Set the name of the output file. If none is give, this will just be the STL file with ".png" appended.
        Default: STLFILE.png

    --quiet
        Suppress output of dimensions and resolutions.

Pngcam-render is a program by James Stanley. You can email me at james\@incoherency.co.uk or read my blog at https://incoherency.co.uk/
};

    exit 0;
}
