#!/usr/bin/perl

use strict;
use warnings;

use Pngcam;
use Getopt::Long;

# all options, with defaults:
my $tool_shape = 'ball';
my $tool_diameter = 6; # mm

my $step_down = 100; # mm
my $step_over = 5; # mm
my $xy_feedrate = 400; # mm/min
my $z_feedrate = 50; # mm/min
my $rapid_feedrate = 10000; # mm/min
my $spindle_speed = 10000; # rpm

my $roughing_only = 0;
my $clearance = 0; # mm
my $rapid_clearance = 5; # mm
my $route = 'both';

my $width; # mm
my $height; # mm
my $depth = 10; # mm

GetOptions(
    'tool-shape=s' => \$tool_shape,
    'tool-diameter=f' => \$tool_diameter,

    'step-down=f' => \$step_down,
    'step-over=f' => \$step_over,
    'xy-feed-rate=f' => \$xy_feedrate,
    'z-feed-rate=f' => \$z_feedrate,
    'rapid-feed-rate=f' => \$rapid_feedrate,
    'speed=f' => \$spindle_speed,

    'roughing-only' => \$roughing_only,
    'clearance=f' => \$clearance,
    'rapid-clearance=f' => \$rapid_clearance,
    'route=s' => \$route,

    'width=f' => \$width,
    'height=f' => \$height,
    'depth=f' => \$depth,

    'help' => sub { help() },
    'usage' => sub { help() },
) or help();

help() if @ARGV != 1;
my $image_file = shift @ARGV;

# default width in mm if none is given
$width = 100 if !defined $width && !defined $height;

die "unrecognised tool shape (expected 'ball' or 'flat')" if $tool_shape !~ /^(ball|flat)$/;
die "unrecognised route (expected 'horizontal', 'vertical', or 'both')" if $route !~ /^(horizontal|vertical|both)$/;

my $pngcam = Pngcam->new(
    tool_shape => $tool_shape,
    tool_diameter => $tool_diameter,

    step_down => $step_down,
    step_over => $step_over,
    xy_feedrate => $xy_feedrate,
    z_feedrate => $z_feedrate,
    rapid_feedrate => $rapid_feedrate,
    spindle_speed => $spindle_speed,

    roughing_only => $roughing_only,
    clearance => $clearance,
    rapid_clearance => $rapid_clearance,
    route => $route,

    width => $width,
    height => $height,
    depth => $depth,

    image_file => $image_file,
);
$pngcam->run;

sub help {
    print qq{Usage: pngcam [options] PNGFILE > GCODEFILE

Tool options:

    --tool-shape flat|ball
        Set the shape of the end mill.
        Default: ball

    --tool-diameter MM
        Set the diameter of the end mill in mm.
        Default: 6

Tool control options:

    --step-down MM
        Set the maximum step-down in mm. Where the natural toolpath would exceed a cut of this depth, multiple passes are taken instead.
        Default: 100

    --step-over MM
        Set the distance to move the tool over per pass in mm.
        Default: 5

    --xy-feed-rate MM/MIN
        Set the maximum feed rate in X/Y plane in mm/min.
        Default: 400

    --z-feed-rate MM/MIN
        Set the maximum feed rate in Z axis in mm/min.
        Default: 50

    --rapid-feed-rate MM/MIN
        Set the maximum feed rate for rapid travel moves in mm/min.
        Default: 10000

    --speed RPM
        Set the spindle speed in RPM.
        Default: 10000

Path generation options:

    --roughing-only
        Only do the roughing pass (based on --step-down) and do not do the finish pass. This is useful if you
        want to use different parameters, or a different tool, for the roughing pass compared to the finish pass.
        Default: do the finish pass as well as the roughing pass

    --clearance MM
        Set the clearance to leave around the part in mm. Intended so that you can come back again with a finish pass to clean up the part.
        Default: 0

    --rapid-clearance MM
        Set the Z clearance to leave above the part during rapid moves.
        Default: 5

    --route horizontal|vertical|both
        Set whether the tool will move in horizontal lines, vertical lines, or first horizontal followed by vertical.
        Default: both

Heightmap options:

    --width MM
        Set the width of the image in mm. If height is not specified, height will be calculated automatically to maintain aspect ratio. If neither are specified, width=100mm is assumed.
        Default: 100

    --height MM
        Set the height of the image in mm. If width is not specified, width will be calculated automatically to maintain aspect ratio. If neither are specified, width=100mm is assumed.
        Default: N/A

    --depth MM
        Set the total depth of the part in mm.
        Default: 10

Pngcam is a program by James Stanley. You can email me at james\@incoherency.co.uk or read my blog at https://incoherency.co.uk/
};

    exit 0;
}
